#!/usr/bin/env perl6
#
use v6;

# Running the pod file will create a pdf using wkhtmltopdf
#
my Str $pod = "$*PROGRAM";
my Str $pdf = $pod;
$pdf ~~ s/\. <-[.]>+ $/.pdf/;
shell( "perl6 --doc=HTML '$pod' | wkhtmltopdf - '$pdf'");

#-------------------------------------------------------------------------------

=begin pod

=head1 NAME MongoDB::Collection - Operations on a MongoDB Collection

=head1 SYNOPSIS

=begin nested
=begin code

use MongoDB;

# Initialize
#
my $connection = MongoDB::Connection.new( );
my $database = $connection.database( 'test' );
my $collection = $database.collection( 'perl_users' );


=end code
=end nested


=head1 DESCRIPTION

This set of modules will help you accessing a MongoDB server. All primitive
functions are installed to insert, update, find and remove documents.
http://docs.mongodb.org/meta-driver/latest/legacy/mongodb-wire-protocol/



=head1 METHODS

=end pod

